### PR TITLE
Have only the main nupkg as artifact

### PR DESCRIPTION
**Pull request by tpluscode**
...as we don't want to publish the others to DNN's NuGet feed

### CODE REVIEW

**Comment by tpluscode** [comment]
cc @ahoefling

**Comment by SkyeHoefling** [comment]
This change won't work, you can't plug in the environment variables like you did it will be best to update the powershell script to just produce 1 build artifact. Let's abandon this PR and I'll submit a new one later today with the changes needed for #3 and I'll update it to produce just 1 artifact as well

**Comment by tpluscode** [comment]
You're right, I'd hoped it would work.

I updated the appveyor file to slightly change how we calculate the build number and push the desired artifact with the PowerShell API

**Comment by SkyeHoefling** [comment]
Do you still need me to update the powershell build script then?

**Comment by tpluscode** [comment]
If you could change the package name that would be awesome

**Pull request merged**
